name: "Next CMS Starter Kit"
description: "A Drupal recipe to use with the JAKALA Next CMS Starter Kit front end."
type: "Site"

recipes:
  # Core
  - core/recipes/tags_taxonomy
  - core/recipes/image_media_type
  - core/recipes/basic_html_format_editor
  - core/recipes/full_html_format_editor
  - core/recipes/restricted_html_format
  - core/recipes/administrator_role
  - core/recipes/content_editor_role
  - core/recipes/core_recommended_maintenance

install:
  # Core
  - block_content
  - config
  - content_translation
  - contextual
  - datetime
  - editor
  - field_ui
  - file
  - help
  - history
  - language
  - link
  - menu_link_content
  - menu_ui
  - node
  - options
  - views_ui
  # Contrib
  - gin
  - gin_toolbar
  - pathauto
  - paragraphs
  - redirect
  - simple_oauth
  - view_unpublished
  # Decoupled contrib
  - decoupled_preview_iframe
  - visual_editor
  - visual_editor_paragraphs
  - graphql_compose
  - graphql_compose_edges
  - graphql_compose_image_style
  - graphql_compose_menus
  - graphql_compose_routes
  - graphql_compose_users
  - graphql_compose_views
  - graphql_compose_preview
  - graphql_compose_fragments

config:
  import:
    # Core
    block_content: "*"
    field_ui: "*"
    file: "*"
    help: "*"
    language: "*"
    menu_ui: "*"
    node: "*"
    user:
      # View to list users.
      - views.view.user_admin_people
    # Contrib
    gin:
      - gin.settings
      - block.block.gin_breadcrumbs
      - block.block.gin_content
      - block.block.gin_help
      - block.block.gin_local_actions
      - block.block.gin_messages
      - block.block.gin_page_title
      - block.block.gin_primary_local_tasks
    pathauto: "*"
    paragraphs: "*"
    redirect: "*"
    simple_oauth: "*"
    # Decoupled contrib
    graphql_compose: "*"

  actions:
    # Set home page
    system.site:
      simpleConfigUpdate:
        page.front: /home
    # Add the Spanish language
    language.entity.es:
      createIfNotExists:
        langcode: en
        status: true
        dependencies: {}
        id: es
        label: Spanish
        direction: ltr
        weight: 1
        locked: false
    language.negotiation:
      simpleConfigUpdate:
        url:
          source: path_prefix
          prefixes:
            en: ""
            es: "es"
          domains:
            en: ""
            es: ""
    # Set and unset Gin blocks.
    block.block.gin_admin:
      simpleConfigUpdate:
        status: false
    block.block.gin_branding:
      simpleConfigUpdate:
        status: false
    block.block.gin_local_actions:
      simpleConfigUpdate:
        region: content
        weight: -10
    block.block.gin_local_tasks:
      simpleConfigUpdate:
        status: false
    block.block.gin_page_title:
      simpleConfigUpdate:
        region: header
        weight: -10
    block.block.gin_primary_local_tasks:
      simpleConfigUpdate:
        region: header
        weight: -5
        settings.secondary: true
    block.block.gin_tools:
      simpleConfigUpdate:
        status: false
    # Update the admin theme to Gin in Theme settings.
    node.settings:
      simpleConfigUpdate:
        use_admin_theme: true
    system.theme:
      simpleConfigUpdate:
        admin: "gin"
        default: "gin"
    # Set permissions for content editor role.
    user.role.content_editor:
      createIfNotExists:
        id: content_editor
      grantPermissions:
        - "use text format basic_html"
        - "use text format full_html"
